apiVersion: apps/v1
kind: Deployment
metadata:
  name: sellers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sellers
  template:
    metadata:
      labels:
        app: sellers
    spec:
      containers:
        - name: sellers
          image: maksymrzd/sellers:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080